### ISSUE TITLE
Just wanna talk with you

### ISSUE THREAD

**Issue by jaxkashif34** [spirobel/aldi#1]
Hey @spirobel I'm sorry for creating an issue I just wanna talk with you on something I mailed you here (spirobel@eprotonmail.com) but seems like you don't use that mail anymore that's why I reached out to you like this again I'm really sorry for that could you please provide me any way to reach out to you? Like any email or whatever you think safe or whatever you like?

**Comment by spirobel** [comment]
what do you want to talk about? I never used this email. Where did you find it?

**Comment by jaxkashif34** [comment]
I found your email on your GitHub profile. After visiting spirobel.github.io, I noticed a follow button with the option to email you, which is how I found that email address.
By the way here is the email body...

Hi Spirobel, I hope you're doing well. I'm Kashif Ali from Pakistan and I came across your profile on GitHub. I'm interested in finding a job in Germany. I'm currently learning German as I aspire to pursue my master's degree there, but financial constraints are a challenge. I'm determined to gather the funds needed for my studies at a German public university, where tuition is free. Could you please assist me in finding a remote job in Germany? It would be a tremendous help, especially since I'm on my own after losing my parents. Any support would be greatly appreciated.
